[package]
org = "ballerinai"
name = "observe"
version = "@toml.version@"
distribution = "2201.12.0"

[platform.java21]
graalvmCompatible = true

[[platform.java21.dependency]]
path = "../native/build/libs/observe-internal-native-@project.version@.jar"
