[package]
org = "ballerinai"
name = "observe"
version = "1.7.2"
distribution = "2201.14.0"

[platform.java25]
graalvmCompatible = true

[[platform.java25.dependency]]
path = "../native/build/libs/observe-internal-native-1.7.2-SNAPSHOT.jar"
